name: Azure Static Web Apps CI/CD

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Set up Node.js version 18
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: npm ci

      # - run: npx nx format:check --verbose

      - run: npx nx affected -t lint --parallel=3

      # - run: npx nx affected -t test --parallel=3 --configuration=ci

      - run: npx nx affected -t build --configuration=production --parallel=3

      - name: Get Affected
        id: get_affected
        run: |
          AFFECTED_APPS=$(npx nx print-affected --select=projects --type=app | sed -e 's/^/|/' -e 's/, /|/g' -e 's/$/|/')
          echo "affected_apps=$AFFECTED_APPS" >> $GITHUB_OUTPUT
          echo "affected_apps=$AFFECTED_APPS"

      - name: Deploy web-app-games
        id: deploy_web_app_games
        if: contains(steps.get_affected.outputs.affected_apps, '|web-app-games|')
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_FIELD_04E7D6E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          skip_app_build: true
          skip_api_build: true
          app_location: '/dist/apps/web-app-games'
          api_location: ''
          output_location: ''

      - name: Get web-app-games url
        id: get_web_app_games_url
        if: contains(steps.get_affected.outputs.affected_apps, '|web-app-games|')
        run: |
          WEB_APP_GAMES_URL="https://icy-field-04e7d6e10.3.azurestaticapps.net"
          if [ ! -z "${{steps.deploy_web_app_games.outputs.static_web_app_url}}"]
          then
            WEB_APP_GAMES_URL="${{steps.deploy_web_app_games.outputs.web_app_games_url}}"
          fi
          echo "web_app_games_url=$WEB_APP_GAMES_URL" >> $GITHUB_OUTPUT
          echo "web_app_games_url=$WEB_APP_GAMES_URL"

      - name: Build web-app
        if: (steps.get_affected.outputs.affected_apps != '||' && !contains(steps.get_affected.outputs.affected_apps, '|web-app|'))
        run: npx nx build web-app:build:production

      - uses: shaneapowell/github-tweak-the-json@v1
        with:
          action: write
          filename: dist/apps/web-app/assets/module-federation.manifest.json
          field: web-app-games
          value: '${{ steps.get_web_app_games_url.outputs.web_app_games_url }}'

      - name: Display dist/apps/web-app/assets/module-federation.manifest.json
        if: (steps.get_affected.outputs.affected_apps != '||')
        run: |
          cat dist/apps/web-app/assets/module-federation.manifest.json

      - name: Deploy web-app
        if: (steps.get_affected.outputs.affected_apps != '||')
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SKY_0B2789003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          skip_app_build: true
          skip_api_build: true
          app_location: '/dist/apps/web-app'
          api_location: ''
          output_location: ''

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequestdeploywebapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SKY_0B2789003 }}
          action: 'close'

      - name: Close Pull Request
        id: closepullrequestdeploywebappgames
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_FIELD_04E7D6E10 }}
          action: 'close'
